# Generated by Django 5.2.1 on 2025-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Потреба')),
            ],
            options={
                'verbose_name': 'Потреба',
                'verbose_name_plural': 'Потреби',
                'ordering': ['id'],
            },
        ),
    ]
