# Generated by Django 5.2.1 on 2025-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('help_text', models.TextField(verbose_name='Допомога')),
            ],
            options={
                'verbose_name': 'Волонтерська допомога',
                'verbose_name_plural': 'Волонтерські допомоги',
                'ordering': ['-id'],
            },
        ),
    ]
