# Generated by Django 5.2.1 on 2025-06-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Розклад занять', max_length=200, verbose_name='Назва розкладу')),
                ('file', models.FileField(upload_to='schedule/', verbose_name='Файл розкладу')),
            ],
            options={
                'verbose_name': 'Файл розкладу',
                'verbose_name_plural': 'Файли розкладу',
            },
        ),
    ]
